language: node_js
node_js:
  - 12
branches:
  only:
    - master
install:
  # - npm install
  true # 什么也不做
before_script:
script:
  # - npm run build
  true # 什么也不做
after_script:
  - return 0
  - pwd
  - ls -al
