anguage: node_js
node_js:
  - 12
branches:
  only:
    - master
install:
  # - npm install
  true # 什么也不做
before_script:
script:
  # - npm run build
  true # 什么也不做
after_script:
  - pwd
  - ls -al
  - rm -rf sui.txt
  - git add .
  - git commit -m 'travis'
  - git push
  - return 0
